language: node_js
node_js: node

script:
  - npm run test
  - npm run build

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && codecov

deploy:
  provider: npm
  email: joshfraser91@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: master
